dist: trusty
sudo: required

before_install:
language: python
python:
 - '3.5'
 - '3.6'
install:
 - pip3 install -r requirements.txt
 - pip3 install -U setuptools
 - python3 setup.py install
 - pip3 install coveralls
before_script:
 - sleep 1 # this is just a placeholder
script:
 - coverage run --source=pybo ./test_script.py
after_success: coveralls
